<template>
  <q-page class="fit flex flex-center column" padding style="flex-wrap: nowrap">
    <h4 class="q-ma-xs">Dr. Gary & Belinda Fettke Podcast #16</h4>
    <h5 class="q-ma-sm">
      Interview by:
      <a href="https://www.youtube.com/channel/UCPn4FsiQP15nudug9FDhluA" target="_blank">Ivor Cummins</a>
    </h5>
    <div class="iframe-container">
        <!-- https://youtu.be/p0VwjsZJmYo -->
      <iframeallow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"allowfullscreenframeborder="0"src="https://www.youtube.com/embed/p0VwjsZJmYo"width="100%"
      ></iframe>
    </div>
    <div class="q-ma-md" style="overflow: auto">
      <p>Ivor: 00:00 - We're here at<a href="https://thelowcarbuniverse.com/" target="_blank">Low Carb Universe</a> in Mallorca, Spain. And as you can see, the beautiful backdrop behind us, but, we're still working hard. Don't worry about that. I meeting with this morning with Doctor Gary Fettke and Belinda Fettke who have a very interesting story to tell. So delighted to meet again Gary, Belinda. Thank you for having us. Oh my pleasure. Absolutely. You have a fascinating story. We'll kind of two stories. First your persecution and exoneration. Then you get on to the fascinating kind of background of where all the dietary guidelines came from, and why ultimately you got into trouble. So maybe Gary if you start with that.
      </p>
      <p>Dr. Gary Fettke: 00:40 - Well, a lot of people already know. My story is very similar to <a href="https://en.wikipedia.org/wiki/Tim_Noakes" target="_blank">Tim Noakes</a>. Going back several years, I started challenging hospital food, and particularly, the amount of sugar that was given to my patients. I'm an orthopedic surgeon in Tasmania. For many years I've been looking after the complications of diabetes, and particularly foot ulceration. So, I've been chopping toes off, chopping legs off, for a couple of decades. And ultimately you get sick and tired of it. So I looked at prevention, and quite clearly sugar became the number one problem. So, I started questioning the amount of sugar my patients were getting in hospital. And to this day, if you've got diabetes and in hospital, it's still recommended that you get three desserts per day. So, I said, look this is crazy. This is ridiculous. And I started questioning that. In the process of questioning the sugar in the hospital, in the hospital food and junk food in the hospital.
      </p>
      <p>Dr. Gary Fettke: 01:33 - I started questioning the quality of hospital food and we all know hospital food is lousy and can be improved. So that incurred the wrath of the Dietitians in the hospital and, over a period of time, ultimately I ended up getting reported to the medical board for being dangerous for recommending anti-sugar and low carb, um, and the medical. And then I subsequently got reported again by another Dietitian for inappropriately claiming to reverse someone's diabetes, which I'm guilty of. Okay. We did reverse his diabetes and only came off five medications, lost 20 kilos and all of that. So, and then there was a third notification to the medical board, which ultimately got dismissed. But the first two were taken very seriously and over a couple of years, two and a half years, I was investigated. And a decision was made against me to say that I'm not allowed to advise my patients as an orthopedic surgeon to reduce their sugar intake even, even if it was shown to be best practice.
      </p>
      <p>Dr. Gary Fettke: 02:35 - And that was a decision that was made lifelong and non-appealable. So obviously, you know, once you see the results of low carb for your patients, you can unsee them. So, I've never stopped talking about it. And if, and with the support of Belinda with her research and with the support of social media and the community, we've kept on challenging that. And, it's involved two Senate inquiries at a national level. It's involved the national ombudsman and after two more years of appealing, my non-appealable decision. It's crazy. We can't go to the supreme court, like they couldn't use the judicial system to appeal it, but we could go to the national health ombudsman to see if there's a problem with the process. That was all she could rule on and she couldn't say. So we showed that there were problems in the process, which clearly there were, and Belinda will allude to those and ultimately was sent to an independent medical board. And I looked at it for six weeks and I tossed it all out and said, this is ridiculous. Not alleged side that I wasn't guilty of anything. They've actually apologized. Now that's uh, that's, uh, almost unheard of that they actually get an apology from the medical board. But ultimately, we lost five years of being dragged through the system. And in that timeframe, my lecturing the students was taken away. My research was curtailed and we've been stuck in that limbo. But in the same timeframe, we've also been, you know, going forward to the public.
      </p>
      <p>Ivor: 04:13 - Yeah, well, it's an incredible job to have gone through all that. Both of you actually, obviously it's your shared, the experience, so to speak. It was all particularly malicious, because I noted at the time, which was incredible. They said that even if the science advanced and you were proven to be correct, you would still remain banned for life from speaking. That's bizarre.
      </p>
      <p>Dr. Gary Fettke: 04:35 - It was completely bizarre. I don't know, obviously I questioned that. And, that's one of the things which the national ombudsman was actually to hang on. Cause she even said, hang on this. This is a, how can you make, how can you, because so many things. I say that science evolves by being challenged, not by being followed. And you know, that's at the bottom of my emails. I mean that's my mantra. So, we have to keep evolving our knowledge. There are things we do today, which are going to be shown to be wrong in the in the future. As had been the past. And so, it was a dumb ruling. And you know. And thank goodness, common sense, spiteful and it was their undoing. Really.
      </p>
      <p>Ivor: 05:22 - Yeah. It's like, it was amazing to me. I've seen a lot of corruption in this whole sphere. Obviously, like yourselves. But that one struck me as bizarre. The thought crossed my mind as well. That's kind of implicating them in the sense. So it did turn out to be. How we got here, then as the older parents of the story. So you're exonerated. And, it's a huge shot in the arm for people all over the world trying to promote healthier food. Like Noakes exoneration, yours, and ANNA Sweden???.
      </p>
      <p>Dr. Gary Fettke: 05:53 - It's literally mine, was the last case to be closed. And so therefore I know that it's pretty well opened the flood gates. I mean I've been contacted by hundreds of doctors who have said, actually, we feel safe now to go, ahead with this and talk about it. And so therefore it has opened the door and it now can become best practice in diabetes management with can become.
      </p>
      <p>Belinda Fettke: - 06:16 He says it can become. But you look on our dietary guidelines, and you look at the Dietitians Association of Australia, which is our peak nutrition body. Yeah. And they still calling low carb a fad. So while the medical board has said yes, I think you can go forward with this, I can't see a problem. The guidelines still a rule books that are not going to allow it to move forward. So,
      </p>
      <p>Dr. Gary Fettke: 06:38 - And that is a great segue into how did we get here with these absurd guidelines. They quite frankly conflict with the science at this point. There's no question. Well let's, take a snapshot of time now. Which is if we look at, we've got an obesity epidemic. We've got an a health crisis on the planet right now. You can see that walking down the street. So we've had in place, dietary guidelines for a long period of time. And one of the arguments is that we don't follow the dietary guidelines. Well we know, we do. If you look at the last 40, 50, years of data, out of the US, out of Australia, out of the UK, we have in fact, increased their cereal in grains. We've decreased our meat. And particularly, red meat consumption. We've done that. So the current dietary guidelines are cereal based, grain based, anti-meat, anti-dairy and rapidly becoming Vegan.
      </p>
      <p>Dr. Gary Fettke: 07:33 - So let's, that's the food pyramid. That's really what's being promoted. And guess what? It hasn't worked. So therefore we've looked to say, look, and obviously low carb, healthy fat, living is not the food pyramid. So, if we accept the fact that the dietary guidelines now have been a complete and utter failure, and have since the McGovern report and the introduction of the Diet, the American dietary goals. Then we've gone back to see how come we've gotten to this situation. Because Belinda said, we're talking, you know, we're all going blue in the face talking about this and Belinda has gone. Well, hang on guys. Why? Why are we being obstructed? Why have I been obstructed? It's got to be in those dietary guidelines. But more importantly, what's influencing them? Turns out that's, the segue in whatever we're doing at the moment isn't working. I'm challenging that. What am I challenging? The guidelines? Or am I challenging the vested interests? And, as it turned out, it's the vested interest that had been blocking myself, and others, in this whole process.
      </p>
      <p>Belinda Fettke: 08:36 - And, I think that. I guessed that it could well be the sugar industry in Australia. We have a very large sugar and wheat industry. So we sort of thought, okay, they're really unhappy about that. So I thought it was a vested interests and, but when I started looking deeper, it was really fascinating. Everyone sort of gotten stuck in this 1977, the change to the low fat guidelines. But, I just kept going back, and it was fascinating. All the way back to, what I've come to understand is, it's the evolution of the, so the evolution of our plant based dietary guidelines, have come from the two arms of the <a href="https://en.wikipedia.org/wiki/Temperance_movement" target="_blank">temperance movement</a>. Which sounds really bizarre. Going all the back to the 18 hundreds. And, in prefacing this conversation, I think it's really important to say that I'm not anti-religion in any way. 
      </p>
      <p>
      Belinda Fettke: 09:25 - Going down, and finding some very strong religious influences on our dietary guidelines, was just something I never expected to find. So, I'm not anti-religion and I'm not anti-vegetarian or Vegan, even. I think people have the right to a choice, whether that's cultural, ethical, or religious ideology. They have that ability to have that choice. In our current society, I would think, and certainly from me, but as I've gone through and looked at their influence, the influence of vested interest, and religious ideology on our dietary guidelines, and particularly the evolution of the plant based, which is I believe a Vegan doctor guidelines. They've taken away my choice. And, they've taken away your choice. And, they've taken away society's choice to eat meat. And it's bizarre. You think? I thought Gary was in trouble for talking about sugar and cereal. But it was actually, he was in trouble for advocating animal protein and animal fats.
      </p>
      <p>
      Ivor: 10:26 - Right. And this story, and I'm broadly familiar with it, although the viewers may not be, it goes back literally to the 18 hundreds. If you do proper detective work, which no one really has, except for Belinda. Can I just say though,
      </p>
      <p>Belinda Fettke: 10:41 - Riece Southern???. There's a young guy in, in America, Riece Southern, has done a lot of research into specifically the seventh day Adventist church dieticians on the dietary guidelines and stuff from about the 1950s a lot of my research I got from him, so I'm not the only person, but he hadn't realized the medical influences. He was specifically Dietitians, but he gave me an amazing segue into, going back. But I then went back even further, because I found that the introduction of the, well, the formation of the American Dietetic Association, was founded by a seventh day Adventist. So you're going even further back, but he'd certainly found a lot of information from the 1950s.
      </p>
      <p>Ivor: 11:28 - All right, great. So if we go to the, the origins of the origin, back in the 18 hundreds, yeah,
      </p>
      <p>Belinda Fettke: 11:35 yeah.</p>

      <p>Ivor: 11:35 Where it really began, this influencing force that, that I guess grew over the century and became more and more organized and more and more modern and subtle in its actions. It started in the late 18 hundreds with a certain lady. I think
      </p>
      <p>Belinda Fettke: 11:51 It actually started right the beginning of the 18 hundreds with aguy called Silvester Graham. And you may have heard of Graham crackers and Graham flour and all those, they will all to stop people being stimulated by caffeine and alcohol and cigarettes and meat. And they believed there was a scientific and political and religious, rationale for vegetarianism. So he was the health reformers of the early 18 hundreds where the start of this rationale, western vegetarianism, is completely different to eastern vegetarianism. Gary will explain that.
      </p>
      <p>Dr. Gary Fettke: 12:25 Eastern vegetarianism is based upon a cultural respect for where the animal sits within the whole food cycle. And even in eastern vegetarianism they will eat some animal produce and then when the animal gets old they'll, you know, for a lot of religions, they will actually eat the animal. But, it's done in a respectful way. And so, eastern vegetarianism is built on centuries of care for the soil, environment, like it and the whole picture. Whereas Western vegetarianism, really only goes back to the early 18 hundreds and it's purely tp stop people. Yeah. To, quell their lust. And it seems strange, but that's what it is. And then that's evolved, into one group, which was the founders of the Adventist Church. Um, and then struggling,
      </p>
      <p>Belinda Fettke: 13:16 they brought those principles of, so it wasn't just stimulants ofagain, um, caffeine and alcohol and cigarettes, but they believeone of the biggest stimulants in our life was meat and it actuallybecame t church doctrine to not eat meat to Stuart bays orpassions. And the most heinous sin of all was masturbation. Sothis is where serials came from. The cereal industry was burstfrom this belief that we that to try and find ways for people tohave, um, uh, protein and different things in their body to, toget rid of meat.
      </p>
      <p>Ivor: 13:56 Right. Because miss was seen and I think the, the, the origins ofthe words, I mean, Karna meet carnal. There's a lot of negativeconnotations in history and I guess they really jumped on thatand saw it has a really big negative influence on is the societylike alcohol or our tanks
      </p>
      <p>Belinda Fettke: 14:17 mate was masturbation. That her very first, her entire book, herfirst book was all, it was a solemn appeal to mothers and how tostop your child masturbating on. The biggest thing was not toput meat on their table and I segwayed. It's sort of differently inmy talks. I really came back and, and talk about the timber tomovement and, and worked out ways because John HarveyKellogg is obviously someone we recognizes, a person involvedwith the cereal industry and he and his brother developed theflight to cereal, but it was so then I said, well yeah, why? Whywas he so intent on developing peanut butters and that madeanalogs and all of these other things. He was at temperancehealth reformer and he was a devout seventh day Adventist. Soyou bring those things down and you think will the, we've gotKellogg's corn flakes from an anti masturbation crusade. Good.Poor old John Harvey Kellogg. Yeah. He's a brilliant individuallyin see greatness in the medical pathway, medical educationreform. That's she patients on food and exercise equipment.But there's a 12 year old,
      </p>
      <p>Dr. Gary Fettke: 15:24 he was invited into the white family and he was type settingthese doctrines. He was type setting, as a twelve year old, thereal cause of masturbation...
      </p>
      <p>Belinda Fettke: 15:35 And that the effect of masturbation was as bad as inwardlydecaying ahead and also like her, her book was horrific. If youread all the things that masturbation could do to you. And hewas 12 years old when he was type setting these books, andtype set for the next, you know, he type set for years for themand wrote or he was actually editing and doing things. Sothere's no wonder by the time he grew up to become a doctor,he had very strong ideas on how bad masturbation was.
      </p>
      <p>Dr. Gary Fettke: 16:06 Following on from that, we, we should state that the weirdthings are now, is it the latest church is the second biggesteducator in the world after the Catholic Church and they areprimary schools, secondary schools, universities, but they prettywell started the dietetics education of the world. They wrotethe textbooks for the first 30 years, heavily involved in thetextbooks, nursing and medicine. They still own 60 publishinghouses and they're pretty well.... And as I said to you recentlythat I've had 6.4 billion downloads of their podcasts in 2016...
      </p>
      <p>Ivor: 16:42 now I'm, I was struck by that figure because I mean, it puts JoeRogan to shame, but 6.4 billion downloads just gives an idea ofthe influence that's occurring. And I think the financials of this -this whole organization that are influencing in so many ways,their financials are quite stunning too - across the world aren'tthey...
      </p>
      <p>Dr. Gary Fettke: 17:06 They own pretty well - they are so involved in the food industryhorizontally and vertically. Uh, acknowledging the, only abouteight weeks ago, the senior members of the Adventist Churchpublished an article in journal called religion acknowledgingvirtually everything we're talking about now. So this is not,they're not hiding it then actually not upset by it. They'reactually proud of what they've been able to achieve. And sothey are, they are the originators of nutrition science. They havebeen heavily involved in our nutritional guidelines since thebeginning because the American Dietetics Association wasformed in October, 1917 by Linda Cooper who wrote thesetextbooks. She worked with John Hart for John Harvey Kellogg.She was an Adventist and a vegetarian and a vegetarian at thattime actually turns out you were Vegan. The term Vegan didn'tturn up until...
      </p>
      <p>Belinda Fettke: 18:00 Vegan wasn't coined until 1944. The Adventist church doctrinewas based on the garden of Eden. They were young Earthcreationists. And so the garden of Eden was um, fruits, nuts,vegetables and saves and so that was all. So there's no history inhunter gatherer. There's no place in their history of, there's noevolution, there's no place in history for meat. So they trulybelieve this is what we should be eating. And
      </p>
      <p>Dr. Gary Fettke: 18:29 so the eating of meat is almost an aberration. It's humans goinga bit crazy. Yes. And driving further craziness and self abuse. It's....I didn't know any of the story obviously before you dug it allup and the other guy, whoever. But I was aware that in theMcGovern commission there was a very influential youngperson who was a vegetarian. I was aware of that fact and Isuspected that - because vegetarian or particularly Veganpeople are extremely motivated ideologically, whereas theaverage person is not, I was always guessing they weredisproportionately represented in guidelines, bodies andanywhere where they could influence, which is okay, I would dothat if I was ideologically motivated. But I think it's just so muchmore huge than we thought
      </p>
      <p>Dr. Gary Fettke: 19:16 They've been working their way up through the system for ahundred years.
      </p>
      <p>Belinda Fettke: 19:21 And can I say when they, a lot of their ideas are amazing. Like itreally is. It's about rest and exercise and a whole lot ... sunlightand community and the anti-alcohol, cigarettes and stimulants.But what's really fascinating is how they've moved together. Soas I say that, the two forms of the temperance movement, onewas the health reformer ones which is the anti-meat group, butthey've joined with the other temperance movement, which isanti-alcohol and has spawned the sugar industry. So not, itdoesn't start the sugar, but it formed these industries of CocaCola and this ice cream Sundaes and chocolate and all thoseother things. So this sweet...and also then putting the sweetinto the cereals, it allowed them to find a way to celebrate asfamily's and big communities and whatever else - and nothaving alcohol. So the Soda Fountains were called the newAmerican bar. It was an ally of temperance. So the food industrythat was creating the sugar and the, and the food industry fromthe Seventh Day Adventists that we're all aligned with thevegetarian substitutes of meat - just match so beautifullytogether - because the sugar gave shelf life to the vegetarianproducts. It doesn't help meat. So yeah, this is where it's allinterconnected. And Harvard University was the start of, um,the nutrition foundation and the school of public health were allstarted by food industry. So five food industries gave money tothis nutrition foundation, which was part of the Harvard Schoolof Public Health. And they worked with the Adventist church todo the very first Adventist studies - because it suits both. Theygrow together and even though they've got very opposing ideasabout things, the interconnection has just helped,
      </p>
      <p>Dr. Gary Fettke: 21:18 ...and this has happened in all of human history. To be honest,it, it seems bizarre what you described, but to be, to me it'sactually makes it makes complete sense because in humanhistory we've always had different sects and organizations whohave common goals, you know who get together even thoughthey might differ significantly on one or two things. So it kind ofall just came together throughout the 20th century that theygrew and grew and power and influence until labor kind ofembedded in all of the structures that the financially, to comeback to that the, the, the cereal industry 101 cereal companieswere formed in Battle Creek, Michigan, which is the home ofthe Adventist church and over time we've effectively gotKellogg's and all of their affiliates, but because they largelyowned by originally by the advantages and I have advancedwork for them, their tires, you can imagine 10% of the profits ofthe cereal industry is going back into the church in Australia.LNG white came to Australia and started a company calledSanitarium, which is Australia's most trusted company.
      </p>
      <p>Belinda Fettke: 22:30 She set up the entire church, but she also wanted to set up thesteel industry as church owned. So that was different. Kellogg'swas a seventh day Adventist and he started his own business,but they actually came to Australia and set the feet into Skypeas a church.
      </p>
      <p>Dr. Gary Fettke: 22:43 Yeah. And that Church owns the biggest cereal company inAustralia and they don't pay any tax, but they put it all back intoeducating the community. So that's where the enormousresources come from to create the billions of podcasts andeverything else. Because the profits are not being taken bycorporate executive types and shareholders to the church. Butthey have this purpose, they believe clearly in what they'redoing. It's all plowed straight back into medical evangelism withcharity status. So it no tax,
      </p>
      <p>Belinda Fettke: 23:21 there's no tax on Sanitarium and they make 462 differentproducts and they don't pay any tax. But
      </p>
      <p>Ivor: 23:26 Sanitarium being the biggest cereal company in Australia. Imean that, I guess I'm just coming back - they are very largeamounts of revenue, indeed - wow.
      </p>
      <p>Dr. Gary Fettke: 23:38 But then they brought (the Adventist church) by Harry Miller,brought uh, soil from Ida, fermented soy to the concept of soilto the Western world. So that modern soy product, which isthat as an alternative to substitute. So we've got fake meat,fake dairy, we've got infant formulas which are madepredominantly from Soy and developed the first infant soyformula. So if you think about the massive impact of soy in thefood cycle and going all the way back to affecting ouragricultural practice, now we're plowing of soil to put in moresoybean that is actually all from the one group. So that wholesoy industry is paying ties back into the one church group. Andthat's where the funding is. And all of this stuff is actually intheir annual reports. I mean, it's not, it's not hidden - significantportions of it. And so you can actually read their annual reports.They've got all the figures. And it talks about the industries theyactually own....
      </p>
      <p>Ivor: 24:47 And I think that is a very important point because along with thedisclaimer, and I'll also echo that one, that vegetarian is fineI've many vegetarian friends. In fact, in our Irish medical groupwe're setting up, um, we have a vegan psychiatrist, a doctor inour group. So it's fine with not to try and influence the wholeworld and the way we're discussing.
      </p>
      <p>Belinda Fettke: 25:11 Yes. But the other is taking away choice. That's, that's the thing.They're taking away a choice by developing these rule booksthat silence my husband
      </p>
      <p>Ivor: 25:22 exactly. The under obviously have I used the word corrupted,but it is corrupted soy refined grains and infant formulas and allthe fake food that's having an enormous negative effect on theworld's health, even though they had good intentions. So this isnot like a conspiracy where it's, it's really on known like twintowers or anything like that where it's really unknown whathappens. All of this is on the record, so we put links to it. It's allhistorical. Just reality. Yeah.
      </p>
      <p>Belinda Fettke: 25:54 And where it's going now is the concern</p>
      <p>Dr. Gary Fettke: 25:58 those two arms have come together. And uh, so when you hearthe term exercise is medicine, which is a brand owned by CocaCola and has come down that whole pathway. So whenever youhear the term exercise medicine, that's a victim into foodindustries,
      </p>
      <p>Belinda Fettke: 26:19 epistatic, Coca Cola, vice president in 1978, the international lifescience institute. So they have got over 400 companies that arefood and pharmaceutical industries plus whatever else,Kellogg's and Coca Cola nicely planted in there. And so thisexercise is medicine is being led by, it's driven by Coca Cola withthe entire LLC in the, in the background. So you can imaginecoca cola is coming this way.
      </p>
      <p>Dr. Gary Fettke: 26:48 And on the other side of it, the new term is called lifestylemedicine. So whenever you hear the term lifestyle medicine,that's pretty well been set up started by the Adventist church.Virtually everyone at the senior level over the last several yearsis actually flowing from the advantage church
      </p>
      <p>Belinda Fettke: 27:05 senior level in America, in Asia, in Australia, and the globalmovement in, in the, um, Europe. I don't believe it's as heavilyinfluenced. So they're just seeing the movement as an amazingthing and joining in. But it's promoting because
      </p>
      <p>Dr. Gary Fettke: 27:22 lifestyle medicine, it's about eating well, sleeping will,moving/exercise and community and bringing that together. Butit is actually when you listen carefully, dissect their message. It'sabout veganism and it is, in fact when you go back to Australia itwas, it's actually owned,
      </p>
      <p>Belinda Fettke: 27:43 The Institute Of lifestyle Medicine is owned by Sanitarium.Sanitarium. Yes. Another circle we come back yet again. So theyput these things into this processed food industry....Dr. Gary Fettke: 27:57 So we've got exercise medicine and lifestyle medicine comingtogether and actually developing the medical curriculum for theworld. And as a result of that, we're seeing, it's already beenintroduced in few universities in the United States and LomaLinda...
      </p>
      <p>Belinda Fettke: 28:15 ...Harvard University and South Carolina Greenville, whichStephen Blair's involved with, and he's been funded by CocaCola in the past with the global energy balance network groupthat's now defunct. So
      </p>
      <p>Ivor: 28:32 these are "Seed universities" ideally expanding to to infiltrate, ifyou will, all of medical education.
      </p>
      <p>Dr. Gary Fettke: 28:40 And we've got lots of examples of where they're spreading outinto the South Pacific, into China, into my own Tasmanian, theuniversity, very core curriculum, which was part of what it was. Ididn't realize I, I tried on a landmine in 2014 when that wasactually being introduced as a test, the test run on the medicalstudents. And I came through and said, actually, that's allnonsense. This is actually, you know, inflammation is caused bysugar, carbs, and poly unsaturated oils,
      </p>
      <p>Belinda Fettke: 29:14 ...and to shut him down even more then they brought "exerciseis medicine" as the trademark into our university. And they'repromoting that. Obviously everything is, you know, "diabetes iscured by exercise as medicine". And I'm just going, oh my gosh.So, so finding out all this has been incredible.
      </p>
      <p>Dr. Gary Fettke: 29:30 It is absolutely incredible. And the thing is the union ofcorporate power and state power is actually the definition offascism. I found that out recently, I never viewed it that way,but that's the definition of fascism. Here interestingly, I'm notsaying it's fascism, but we have the allying of corporate powerand ideological kind of religious interests together, whichbecomes extremely powerful because the huge revenuescoming in can be redirected towards changing the message,changing the whole, the whole perception of everyone. So I'mguessing now that people should really be aware of this andbegin to counter it and counter the fake-food culture that'sbeing generated.
      </p>
      <p>Dr. Gary Fettke: 30:16 I think we know that there's a health issue on the planetobesity, diabetes out of control. And we have an answer whichis healthy eating, eat fresh, local, seasonal food, which actuallyturns out by definition to be low-carb, healthy fat. So we havean answer. We have an antidote. So why isn't it beingpromoted? Why isn't it becoming first line management? Wellnow we know, we've always suspected it's food industry havebeen involved but actually now know the mechanism of howthat's evolved and that the food guidelines is one, but theindustry is another, and they both have actually supported eachother. Not For 10 or 20 or 30 or 40 years. But for a hundredyears and then they build on this history that goes back forprevious 50 60 80 years to the early 1800's, and I call thatgenerational education. You believe what your teachers havetaught to you and your teachers before then. So as a result, thisis just become the norm.
      </p>
      <p>Belinda Fettke: 31:18 And I can just tell you never upset a woman and pick on herhusband. He goes smoothly because look what's happening. Allof those things become revealed. Yeah. If they'd never gone offto Gary and just if the medical board have just gone, this is a bitsilly it let's have a conversation. You know, we want you to getoff social media, whatever else. I've never have looked, but theywas so dogmatic and I just went, you know what? They're nottaking my husband down and I'm going to find out why.Excellent
      </p>
      <p>Dr. Gary Fettke: 31:48 Belinda. And you know, but that's often the way of dogmatists,especially ideologically driven ones. And they will tend to reactvery strongly when they're in any way threatened with Lego.Say lucky they did. And with norcs as well. Looky. They did thatabsurd accusation and now it has blown back on them and the,Belinda Fettke: 32:07 that's what Russ Green found out. He found this exercise asmedicine. Like that's influenced Tim Noakes international lifescience institute is that powerful one that seems to haveaffected Tim Noakes but now we've brought in the fact that it'snot just that it's this as well and Tim was just like, oh my gosh,now I understand why the Vegan movement was so anti whatI'm talking about. And yeah, I think it's so we have layers here ofmarriages made in hell. It's actually over hundreds of yearscreating a dysfunctional family. I did disease, but
      </p>
      <p>Ivor: 32:40 there is one thing though the ILS, I might just call out. I had arun in with people involved with the ILS cy and I wasn't aware ofthem. I was involved in a debate and they found it afterwardsabout the Ilsi from Belinda. Belinda, actually the message thatthe time you tipped me off and I was amazed when I looked upIlsi, it was a think tank, which has always suspect started inAmerica, right around Washington or something, 78 you see athink tank starting, you know that's cooperatives revenue kindof stuff going on. It's just the way it is. But when you look at alltheir directors and the industry side cover every cocacola andNestle Danone, I mean it's just a who's who, Kellogg's old cerealguys and then you look at the other site directors from likeeducation and medicine and all these professors, every countryallied and I just looked and I said, whoa, that's exactly what I do.If I had an interest to make what you are describing happen, ofcourse you would. Key opinion leaders, bring them in, get themon board and talk about research and advancing health and it'salways eat, eat less. If you have a look at all of their programsand carbohydrates and the gospel truth or eat less, move more.It's the classic CECO calories in, calories out deception that CocaCola and all the food companies love.
      </p>
      <p>Dr. Gary Fettke: 34:10 They do listen to them now it's exercise more, eat less.Ivor: 34:16 That's what we've worked out. You know, it all z and thereligion. This is what it thereafter eat. Sorry, move more and eatless meat. Now just to be clear that that is the certainly theintent. That's not technically a phrase yet. No, no.
      </p>
      <p>Dr. Gary Fettke: 34:34 Do you look for it? So I mean they're talking about meat tax Uzinow it was a um, uh, uh, taking dietetic education into China.They're writing the textbooks for Dietitians or dietetics for Chinaat the moment and medicine. So there's things to listen out forit. Now that you know
      </p>
      <p>Ivor: 34:55 specifically say it, less meet -they call it "plant based". But youknow, euphemisms are everywhere.
      </p>
      <p>Dr. Gary Fettke: 35:01 When you hear the terms "plant based Diet." When you hearthe term "Vegan", when you hear the term "exercise asmedicine", when you hear the term "lifestyle medicine" OR"ILSI" - just recognize that they have a history behind them,which is actually based on ideology, ideology, which is nowintertwined with corporate vested interest. And it's not their forour health, it might, it's advertised as such. And they believe init. We don't always agree it's a bit of marriage counseling - Ivorintervene quick! But they believe it's for health. So in fairnessthey, but health and salvation and that's the difference
      </p>
      <p>Ivor: 35:43 mixture. That's always the problem. And, and in fairness, thedisclaimer is very important, not against religion, not againstthese diets. However, the problem, the problem's who religionhistorically for thousands of years, uh, often they've been greatideas with good intentions, but certain dogmas then are whathave caused the issue over over centuries and millennia. Andhere we're seeing, you know, a lot of what they're doing is forthe right reason. It's good stuff on. Unfortunately it's justcarrying with as a Trojan horse of something that's completelyirrational and anti scientific and that's being carried through.
      </p>
      <p>Dr. Gary Fettke: 36:21 I think that's perfect. That's it. I just got up off to the wrongstart. So you know, occasionally you might drive up the highwayon the wrong side and sooner or later you'll work out that, hangon, we've gotten, we're in trouble
      </p>
      <p>Ivor: 36:36 or less. You get the whole world to switch the sides, which youdrive od, which it looks like what they're trying to do
      </p>
      <p>Dr. Gary Fettke: 36:43 because I realized we're in trouble, but I actually think, youknow, there's this head on collision that's about to happen anduh, if you, if we understand history, I mean I, I looked at heraghast. I went, what? There's barriers either as a and thenbefore know, I know, but when you first read baby Gary firsthaired, the stuff he's saying, hold on a minute. Are you sure hecome home from work and I go, you ain't funny, fun a fannedout today. I spoke out about this at the crossfit games last year.They killed conference in and I said to Belinda, I need to nowrecheck all this before I'm going to say it out loud. He'd beenlistening to me just believing me. And, and so I've got all thereferences. So all that talk was completely referenced. Butbefore that we actually popped in and saw, I rang up Zoe.
      </p>
      <p>Dr. Gary Fettke: 37:29 This is Zoe. I'm going to drag her in. I said, Zoe, can we comeand have a chat to you? So we traveled from Australia to Wiles,uh, Zoe and Andy and Maraica sobers came up from Cape Townand we sat there in their house for five days and said, are wecrazy? Can we just check it all with you? And so we had fivelaptops going all cross referencing and they actually agree,yeah, you're actually right. We're not making it up. And then thetalk was given, it's been acknowledged repeatedly since then bymembers of the Adventist church. We've got a lot of exitvendors to have come along and said, you're absolutely right.They'd probably be my biggest supporters now. Like some ofthe people who had contacted me the most and talk to me andthis, it just makes sense. I hadn't realized. And, and then, andthen in most recent times, this acknowledgement by theAdventist church that what we're talking about is actuallycompletely relevant. So as we all move forward, it's justimportant to know if someone comes to your table that whathat they're wearing. Yeah. And I think in going forward, ideologyalso needs to be discussed as a conflict of interest
      </p>
      <p>Belinda Fettke: 38:36 in nutrition science because it's, it's having a huge influence.</p>
      <p>Ivor: 38:40 I actually love that point, Belinda to so many important pointshere. It's dizzying. But that one is huge in itself because anideological driver for, for a human being is much more powerfulthan simply some extra money. True classic conflict of interest.The coi is we see influencing Madison and there are studies onthis can sometimes on the amount to a few thousand dollars ayear and gifts to doctors I'm sure, but ideology is a much morepowerful driver of a human than any more than it comes fromthe heart. And it's part of your, your essential intent. We usedto call it in management. Uh, but that's a huge point. Conflict ofinterest should include if you have religious and ideologicalbeliefs that, that that clearly would affect your, your, your biastowards certain,
      </p>
      <p>Belinda Fettke: 39:29 this is where it is, you know, there's a huge conflict of interestand it just needs to be acknowledged. And, uh, and I, in goingforward, if we are creating, I mean, do we need guidelines at allbut for sick people, if we're going forward and creatingguidelines, it needs, you know, we may need those peoplewho've got incredible experience in a Vegan Diet to be helpingwrite that part of the dietary guidelines, but acknowledgingthem their beliefs and then people who want to talk about lowcarb, we need to get those people in, not the people who havegot the Vegan interests doing the low carb. You know, it's, it'sabout creating fairness I think.
      </p>
      <p>Ivor: 40:06 And transparency, transparency, transparency above all whereeveryone is as laid out in the table where they're coming from.Yeah. Very good. Well, I think that's going to begin thehappening in the coming years. The race I've switch all of thisgets resolved is the debate. I think, I know talking to a DrSeinfeld about this a few times over the years, will it takearound 10 years to largely get more clarity, transparency andgood science or will it be faster with the growing low carb onmovement is quite rapid growth. We might close will now, whatdo you think to reach a point where largely things are moretransparent and the general public have more of a grasp on
      </p>
      <p>Dr. Gary Fettke: 40:49 hi, I'd like to think it's going to happen tomorrow, but it's goingto take a lot longer. I think there are so many forces out therethat we can't change the world we'd like to, but we can asindividuals make a decision about what we do this afternoonand tomorrow we can do that for our families and that all of thework we're doing is to support those people in want to make adifference. And so yes, it, you know, it'd be nice to save theworld, but we're going to need to start with saving ourselvesfirst of all. Um, and a lot of the resources for this and the twoare billionaires put together just to let you know, and it's on the,I support gary.com site so that we're making it all public. It's all,I created a website
      </p>
      <p>Belinda Fettke: 41:34 really annoyed Afra no doubt. I created a website saying Isupport gay. And I've just started putting all these things up andit's been really interesting. Like journalists have contacted me,the u s right to know has recently contacted me. They wantedto know about the cereal, um, documents that I've uncovered.So it's quite fascinating creating a website that just supportsyour husband is something they never expect.
      </p>
      <p>Ivor: 41:56 It was Super Rubia and that's the beauty of the modern, youknow, Internet environment where, where people can fightback with inflammation against misinformation. So, so that's afantastic platform. And I guess when we release this, I put thelinks also. And I also think if we did, we mentioned this before, aa nice kind of a family tree going back to the 1800 stills with thekey players and interconnections. Maybe that's, that'ssomething to be good to work with you on that. Excellent. We'lldo that for transparency. Oh, that's crazy. Not for going afteranyone for transparency and honesty. Did it. Great. Thanks.Hey, fantastic job. Great job you guys. Thanks. Bye.
      </p>
    </div>
  </q-page>
</template>

<script>
export default {
  name: "DrFettke_116"
};
</script>
<style scoped>
.iframe-container {
  position: relative;
  width: 100%;
  padding-bottom: 56.25%;
  height: 0;
}
.iframe-container iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
</style>